version: '3'

services:
  frontend:
    image: frontend:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3

  backend:
    image: backend:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 3

  database:
    image: database:latest
